name = "MinkowskiReduction"
uuid = "d617d09d-b3c0-43f1-8886-30d89b900f25"
authors = ["Gus Hart"]
version = "1.3.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
